name: build App
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
              node-version: [10.x, 12.x]

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
            node-version: ${{ matrix.node-version }}

        - name: Cache Node Repository
          uses: actions/cache@v1
          with:
            path: ./node_modules
            key: jetlinks-ui-antd-repository
        - name: Install
          run: |
            npm install
            npm run-script build
            cp -r dist ./docker/
            cd docker
            sh ./build
            docker build -t registry.cn-shenzhen.aliyuncs.com/jetlinks/jetlinks-ui-antd:1.0-SNAPSHOT .

        - name: Build and Deploy
          uses: jetlinks/jetlinks-ui-antd@dynamicRender
        
        - name: Login Docker Repo
          run: echo "${{ secrets.ALIYUN_DOCKER_REPO_PWD }}" | docker login registry.cn-shenzhen.aliyuncs.com -u ${{ secrets.ALIYUN_DOCKER_REPO_USERNAME }} --password-stdin
        
        - name: Push Docker
          run: docker push registry.cn-shenzhen.aliyuncs.com/jetlinks/jetlinks-ui-antd:1.0-SNAPSHOT